<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [66]:
import numpy as np

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [67]:
array_1D = np.arange(0,10,1)

array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [68]:
array_2D = np.copy(array_1D)
array_2D_reshape = array_2D.reshape(2,5)

print(array_2D_reshape)


[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [69]:
array_dist_0 = np.array([0, 2, 0, 3, 0, 4, 0])
indices = [i for i, elemento in enumerate(array_dist_0) if elemento>0]

print (f"Los indices son {indices}")

Los indices son [1, 3, 5]


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [70]:
array_aleatorio_3x3 = np.random.rand(3,3)

array_aleatorio_3x3

array([[0.70925192, 0.75839836, 0.78616475],
       [0.04498344, 0.29520409, 0.09725334],
       [0.65802888, 0.62371932, 0.42700656]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [71]:
array_aleatorio_10= np.random.randint(0, 25, (1,2, 5))
max = np.max(array_aleatorio_10)

min = np.min(array_aleatorio_10)

print (f"El array generado es \n{array_aleatorio_10}\n")
print (f"El valor maximo es {max}")
print (f"El valor minimo es {min}")

El array generado es 
[[[ 9  7  4  5  5]
  [ 0  3 18 17 15]]]

El valor maximo es 18
El valor minimo es 0


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [72]:
a_prev_inv= np.array([1, 2, 3, 4, 5, 6])

a_inv = a_prev_inv[::-1]

a_inv

array([6, 5, 4, 3, 2, 1])


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [73]:
a_trid = np.random.randint(0, 25, (2,3, 4))
var15 = np.where(a_trid == 15)

elem_1er_array = a_trid[0,:, :]
ultima_fila = a_trid[1,2,:]

print (f"- el array aleatorio es \n{a_trid}")
print (f"\n- el primer valor 15 se encuentra en {var15}")
print (f"\n- los elementos del primer array son \n{elem_1er_array}")
print (f"\n- la ultima fila del ultimo array es \n{ultima_fila}")

- el array aleatorio es 
[[[ 4  1 24 14]
  [ 0  2  5 21]
  [14 15 15 15]]

 [[19 14 11 24]
  [ 1 16  3 16]
  [22  5  4 22]]]

- el primer valor 15 se encuentra en (array([0, 0, 0]), array([2, 2, 2]), array([1, 2, 3]))

- los elementos del primer array son 
[[ 4  1 24 14]
 [ 0  2  5 21]
 [14 15 15 15]]

- la ultima fila del ultimo array es 
[22  5  4 22]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [74]:
b_trid = np.random.randint(1, 31, (3,2, 5))
sub_array= b_trid[0,:,:2]
sub_total = b_trid [1:,:,:]

print(f"Array 3 x 2 x 5 = \n {b_trid}")
print(f"\nlos dos primeros elementos de cada fila del primer array = \n {sub_array}")
print(f"\nsubarray que contiene todas las filas de los dos últimos arrays = \n {sub_total}")

Array 3 x 2 x 5 = 
 [[[ 7 21 11 30 23]
  [ 4 24 19  9 24]]

 [[11 11 19 25 17]
  [ 2 14 26 14 24]]

 [[20  5 27 25 19]
  [21 23 21 19 29]]]

los dos primeros elementos de cada fila del primer array = 
 [[ 7 21]
 [ 4 24]]

subarray que contiene todas las filas de los dos últimos arrays = 
 [[[11 11 19 25 17]
  [ 2 14 26 14 24]]

 [[20  5 27 25 19]
  [21 23 21 19 29]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [75]:
c_trid = np.random.randint(1, 25, (4,3,2))

print(f"Array 4 x3 x2 = \n \n{c_trid}")


Array 4 x3 x2 = 
 
[[[ 1 16]
  [17  8]
  [15  8]]

 [[ 5 23]
  [ 9 12]
  [11 16]]

 [[21 18]
  [ 7 20]
  [11  8]]

 [[14  1]
  [23 18]
  [ 9 23]]]


In [76]:
## Cambia todos los elementos de la segunda fila del segundo array por `0`.

c_trid[1, 1, :] = 0

# Imprimir el resultado
print("Array tridimensional después de la modificación:")
print(c_trid)

Array tridimensional después de la modificación:
[[[ 1 16]
  [17  8]
  [15  8]]

 [[ 5 23]
  [ 0  0]
  [11 16]]

 [[21 18]
  [ 7 20]
  [11  8]]

 [[14  1]
  [23 18]
  [ 9 23]]]


In [77]:
##- Cambia todos los valores del último array a `-1`.

c_trid[3,:,:] = -1

# Imprimir el resultado
print("Array tridimensional después de la modificación:")
print(c_trid)

Array tridimensional después de la modificación:
[[[ 1 16]
  [17  8]
  [15  8]]

 [[ 5 23]
  [ 0  0]
  [11 16]]

 [[21 18]
  [ 7 20]
  [11  8]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [78]:
d_trid = np.random.randint(-10, 14, (2, 4, 3))
print("FILTRACION DE MAYORES DE 5")
mascara = d_trid > 5
filtrado5=  d_trid[mascara]
print(f"Array 2x 4x 3 que vamos a trabjar = \n \n{d_trid}")
print(f"\ncreamos mascara booleana de mayores de 5 \n{mascara}")
print(f"\naplicamos mascara a d_trid  \n{filtrado5}")



FILTRACION DE MAYORES DE 5
Array 2x 4x 3 que vamos a trabjar = 
 
[[[ 11   5  12]
  [ -8  -7   8]
  [ -4   2   2]
  [ 13 -10 -10]]

 [[ -2  -5  -9]
  [ -8   9  12]
  [  7   5  -2]
  [  6   1   6]]]

creamos mascara booleana de mayores de 5 
[[[ True False  True]
  [False False  True]
  [False False False]
  [ True False False]]

 [[False False False]
  [False  True  True]
  [ True False False]
  [ True False  True]]]

aplicamos mascara a d_trid  
[11 12  8 13  9 12  7  6  6]


In [79]:
print("\n \nReemplaza todos los elementos negativos por `0`")

e_trid = np.random.randint(-10, 14, (2, 4, 3))
print(f"la matriz que utilizaremos es \n{e_trid}\n")

e_trid_filtrado=np.where(e_trid[:,:,:] < 0, 0, e_trid)
print(f"\nigualando a 0 los valores negativos \n{e_trid_filtrado}\n")


 
Reemplaza todos los elementos negativos por `0`
la matriz que utilizaremos es 
[[[-10   0  13]
  [ -3   9  -1]
  [  0   4   8]
  [ -2   4  -1]]

 [[  3   8   8]
  [ -1  10   6]
  [  4  -3   9]
  [ -6   6  -8]]]


igualando a 0 los valores negativos 
[[[ 0  0 13]
  [ 0  9  0]
  [ 0  4  8]
  [ 0  4  0]]

 [[ 3  8  8]
  [ 0 10  6]
  [ 4  0  9]
  [ 0  6  0]]]



#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [80]:
f_trid = np.random.randint(1, 28, (3, 3, 3))
print(f"array a utilizar\n {f_trid}\n")

sub_2_2c = f_trid[1,:,:2]
print(f"subarray del segundo array que contenga solo las dos primeras columnas \n{sub_2_2c}")


resultado = np.where(f_trid[2,:,:]>20)
print(f"\nelementos del tercer array que sean mayores que `20` {resultado}")

array a utilizar
 [[[12  4 19]
  [15 27  3]
  [20 19 24]]

 [[16  8 17]
  [10 17 12]
  [13  4 12]]

 [[ 7 21 12]
  [ 8 21  3]
  [24  5 16]]]

subarray del segundo array que contenga solo las dos primeras columnas 
[[16  8]
 [10 17]
 [13  4]]

elementos del tercer array que sean mayores que `20` (array([0, 1, 2]), array([1, 1, 0]))


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [81]:
a_random = np.random.randint(1, 101, (2,5))
a_max = np.max(a_random)
a_min = np.min(a_random)
print (f"Array a utilizar \n{a_random}\n")

a_random[a_random == a_max] = 0
a_random[a_random == a_min] = 0
print (f"\nArray modificado \n{a_random}")
print (f"\nmaximo remplazado por 0: {a_max}")
print (f"minimo remplazado por 0: {a_min}")

Array a utilizar 
[[ 41  74  56  10 100]
 [ 69  55  80  79  79]]


Array modificado 
[[41 74 56  0  0]
 [69 55 80 79 79]]

maximo remplazado por 0: 100
minimo remplazado por 0: 10


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [82]:
a_15 = np.random.randint(1, 100, (2,3,5))
print (f"Array a utilizar \n{a_15}")

a_15_ordenado = np.sort(a_15)
print(f"\nEl array ordenado ascendendete quedo : \n{a_15_ordenado}")

Array a utilizar 
[[[ 1 11 82 54 36]
  [38 96 19 28 10]
  [87 21 66 48  8]]

 [[40 36 92 87 49]
  [53 56 83 90 10]
  [98 27  4 86 70]]]

El array ordenado ascendendete quedo : 
[[[ 1 11 36 54 82]
  [10 19 28 38 96]
  [ 8 21 48 66 87]]

 [[36 40 49 87 92]
  [10 53 56 83 90]
  [ 4 27 70 86 98]]]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [83]:
a_4x4 = np.random.randint(1, 100, (4,4))
print (f"Array a utilizar \n{a_4x4 }")

suma_columnas = np.sum(a_4x4, axis = 0)
print (f"\nla suma de columnas da:  \n{suma_columnas }")

suma_filas = np.sum(a_4x4,axis=1)
print (f"\nla suma de filas da:  \n{suma_filas }")

Array a utilizar 
[[31 65 15 19]
 [21  8 49 21]
 [66 40 65 60]
 [43 92 66 94]]

la suma de columnas da:  
[161 205 195 194]

la suma de filas da:  
[130  99 231 295]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [84]:
a_bordes = np.zeros((5, 5))

a_bordes[0, :] = 1       
a_bordes[-1, :] = 1      
a_bordes[:, 0] = 1       
a_bordes[:, -1] = 1      


print(f"Matriz 5x5 con bordes de 1 y interior de 0: \n {a_bordes}")

Matriz 5x5 con bordes de 1 y interior de 0: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [85]:
a_med_std = np.random.randint(1, 100, (2,5))
print(f"array a utilizar : \n{a_med_std}\n")

media = np.mean(a_med_std)
desv_std=np.std(a_med_std)

print(f"La media del array es: {media}")

print(f"El desvio estandar es: {desv_std.round(2)}")

array a utilizar : 
[[45  4 96 93 30]
 [15 57 26  9 56]]

La media del array es: 43.1
El desvio estandar es: 30.98


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [86]:
a_3d = np.random.randint(1, 25, (2, 3, 4))
print(f"El array a utilizar es:\n {a_3d}")

a_3d_transp = np.transpose(a_3d)
print(f"\n\nEl array transpuesto es:\n {a_3d_transp}")

El array a utilizar es:
 [[[ 2 15 22 23]
  [24 15 13 22]
  [ 3  3 15 16]]

 [[ 7  3 24 11]
  [14 20 10  7]
  [ 3 13  2  2]]]


El array transpuesto es:
 [[[ 2  7]
  [24 14]
  [ 3  3]]

 [[15  3]
  [15 20]
  [ 3 13]]

 [[22 24]
  [13 10]
  [15  2]]

 [[23 11]
  [22  7]
  [16  2]]]


#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [87]:
a_3d_v2 = np.random.randint(1, 25, (3, 4, 2))
print(f"El array a utilizar es:\n {a_3d_v2}")

a_3d_v2_transp = np.transpose(a_3d_v2, (1,0,2))
print(f"\n\nEl array transpuesto con formota 4 3 2:\n {a_3d_transp}")

El array a utilizar es:
 [[[10 17]
  [14 24]
  [14 16]
  [ 9 22]]

 [[ 9 14]
  [ 7 20]
  [ 6 23]
  [ 5 15]]

 [[ 7  2]
  [21 17]
  [ 9  2]
  [19 10]]]


El array transpuesto con formota 4 3 2:
 [[[ 2  7]
  [24 14]
  [ 3  3]]

 [[15  3]
  [15 20]
  [ 3 13]]

 [[22 24]
  [13 10]
  [15  2]]

 [[23 11]
  [22  7]
  [16  2]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [88]:
a_3d_v3 = np.random.randint(1, 25, (3, 2, 4))
print(f"El array a utilizar es:\n {a_3d_v3}")

a_3d_v3_transp = np.transpose(a_3d_v3, (2,1,0))
print(f"\n\nEl array transpuesto con formota 4 3 2:\n {a_3d_transp}")

El array a utilizar es:
 [[[13 12 24 14]
  [18 11 21  5]]

 [[ 5 23  4 10]
  [17  9  6 15]]

 [[16 13 11 22]
  [10 22 20  9]]]


El array transpuesto con formota 4 3 2:
 [[[ 2  7]
  [24 14]
  [ 3  3]]

 [[15  3]
  [15 20]
  [ 3 13]]

 [[22 24]
  [13 10]
  [15  2]]

 [[23 11]
  [22  7]
  [16  2]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [89]:
a_ej17 = np.random.randint(-10, 11, (3, 4, 5))
print(f"El array a utilizar es:\n {a_ej17}")

mediana = np.median(a_ej17)
max_a_ej17 = np.max(a_ej17)
min_a_ej17 = np.max(a_ej17)
print(f"la mediana es: {mediana}")
print(f"El valor maximo es: {max_a_ej17}")
print(f"El valor minimo es: {min_a_ej17}\n")

final = np.empty(a_ej17.shape, dtype=object)

final[a_ej17 == mediana] = "M"
final[a_ej17 > mediana] = "X"
final[a_ej17 < mediana] = "Y"
final[a_ej17 == max_a_ej17] = "MAX"
final[a_ej17 == min_a_ej17] = "MIN"


print(f"\nEl array modificado es:\n{final}")


El array a utilizar es:
 [[[ -6   1   2  -2   7]
  [ -5  -9 -10   7  -4]
  [  5   1  -3  -2  -2]
  [  6  -7  -6  -3   0]]

 [[ -7   7  -3  -1   9]
  [ -4   1   0  -5   6]
  [-10   9  -8  -2   5]
  [  1   0   1   5   3]]

 [[ -2  -6   8  -4  -2]
  [  4  -9   4   0 -10]
  [  7   5  -9   4   6]
  [  8   0  -3  -7   8]]]
la mediana es: 0.0
El valor maximo es: 9
El valor minimo es: 9


El array modificado es:
[[['Y' 'X' 'X' 'Y' 'X']
  ['Y' 'Y' 'Y' 'X' 'Y']
  ['X' 'X' 'Y' 'Y' 'Y']
  ['X' 'Y' 'Y' 'Y' 'M']]

 [['Y' 'X' 'Y' 'Y' 'MIN']
  ['Y' 'X' 'M' 'Y' 'X']
  ['Y' 'MIN' 'Y' 'Y' 'X']
  ['X' 'M' 'X' 'X' 'X']]

 [['Y' 'Y' 'X' 'Y' 'Y']
  ['X' 'Y' 'X' 'M' 'Y']
  ['X' 'X' 'Y' 'X' 'X']
  ['X' 'M' 'Y' 'Y' 'X']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [90]:
ej18 = np.random.randint(0, 2, (4, 4))
print(f"El array a utilizar es:\n {ej18}")

fila_igual_columna = False

for i in range (ej18.shape[0]):
    for j in range (ej18.shape[1]):
        iguales = True
        for k in range(ej18.shape[0]):
            if ej18 [i,k] != ej18[k,j]:
                iguales = False
                break
        if iguales:
            fila_igual_columna=True
            print(f"La fila {i} es igual a la colum {j}")
            break
    if fila_igual_columna:
        break
if not fila_igual_columna:
    print("no hay filas iguales")

El array a utilizar es:
 [[0 1 0 0]
 [1 1 1 0]
 [1 0 1 0]
 [0 0 1 0]]
no hay filas iguales
